app:
    http:
        host: 172.16.6.73
        port: 8087
    sockJs:
        host: 172.16.6.73
        port: 8383
        endPoint: /sockjs/*

    clientSubUrl_TopicAll: clientSubUrl.topicAll
    clientSubUrl_TopicSpec: clientSubUrl.topicSpec

# ===================================================================
# ActiveMQ
# ===================================================================
spring:
   activemq:
     broker-url: tcp://172.16.6.73:61616?jms.prefetchPolicy.queuePrefetch=1
     user:
     password:

# ===================================================================
# CORS
# ===================================================================
cors:
    allowedOriginPattern: "*"

# ##########################################################
# IGT
# ##########################################################
IGT:
    appId: LBLBsMp6bb57lh4gk3TSB3
    appKey: LWZdSN2rVz8LrmVMXYqw95
    appToken: tGdYPwvjTs8Oaexi0nGUg3
    host: http://sdk.open.api.igexin.com/apiex.htm
